spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  #mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.offcn.pojo
